server:
  port: 8001
#  ssl:
#    key-store: classpath:mykeystore.jks
#    key-store-type: JKS
#    key-store-password: acgnbbs
#    key-alias: tomcat

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
#  mail:
#    host: smtp.163.com
#    port: 25
#    username: lww500wwl@163.com
#    password: UDRRPUTMCDVKHACR
#    default-encoding: UTF-8
#    properties:
#      mail:
#        debug: true #启动debug调试
#        smtp:
#          auth: true
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
#          ssl:
#            trust: smtp.163.com
#            enable: true
#          starttls:
#            enable: true
#            required: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#mybatis:
#  type-aliases-package: com.yusa.acgnbbs.pojo
#  mapper-locations: classpath:mapper/*.xml
#jwt:
#  secret=secretkey
#  expiration=86400000
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

